<?php

function cipher_menu() {
    $items['cipher'] = array(
        'title' => 'Cipher Shift Example',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['cipher_success_page'] = array(
        'title' => 'Shifted Input',
        'page callback' => 'cipher_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function cipher_form() {
    $form['shift_value'] = array(
        '#title' => 'Shift value',
        '#type' => 'textfield',
        '#description' => t('Please enter your shift number.'),
        '#element_validate' => array('element_validate_integer_positive'),
        '#required' => TRUE,
    );
    $form['shift_direction'] = array(
        '#title' => 'Shift direction',
        '#type' => 'textfield',
        '#description' => t('Please enter a direction (either left or right).'),
        '#element_validate' => array('element_validate_direction'),
        '#required' => TRUE,
    );
    $form['phrase_input'] = array(
        '#title' => 'Phrase Input',
        '#type' => 'textfield',
        '#description' => t('Please enter a phrase you wish to shift.'),
        '#element_validate' => array('element_validate_phrase'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Generate Cipher',
    );

    return $form;
}

function element_validate_direction($element) {
    if (!($element['#value'] === 'left' || $element['#value'] === 'right')) {
        form_error($element, t('Please enter either left or right'));
    }
}

function element_validate_phrase($element) {
    $pattern_mostly_alpha = '/^[A-Z\'".?! ]+$/i';
    if (!preg_match($pattern_mostly_alpha, $element['#value'])) {
        form_error($element, t('Please do not use special characters that are not space or punctuation characters'));
    }
}

function shift_letter($character, $shift) {
    $char_ascii = ord($character);
    $shifted_char = ($char_ascii + $shift) % 26; //26 alphabetical characters
    return chr($shifted_char);
}

function calculate_cipher($shift, $direction, $phrase)
{
    $shift = intval($shift);
    switch ($direction) {
        case 'left':
            $shift = -$shift;
            break;
        default:
            break;
    }

    $shifted_phrase = "";

    for ($char_index = 0; $char_index < count($phrase); $char_index++) {
        $current_char = $phrase[$char_index];
        if (preg_match('/[a-zA-Z]/' , $current_char)) {
            $shifted_phrase = $shifted_phrase . shift_letter($current_char, $shift);
        }
        else {
            $shifted_phrase = $shifted_phrase . $current_char;
        }
    }
    return $shifted_phrase;
}

function cipher_form_submit($form, &$form_state) {
    $shift_value = $form_state['values']['shift_value'];
    $shift_direction = $form_state['values']['shift_direction'];
    $phrase_input = $form_state['values']['phrase_input'];

    $cipher_output = calculate_cipher($shift_value, $shift_direction, $phrase_input);

    $_SESSION['cipher_output'] = $cipher_output;

    $form_state['redirect'] = 'cipher_success_page';
}

function cipher_success() {
    $answer = $_SESSION['cipher_output'];
    return 'Your shifted phrase is: ' . strtolower($answer);
}
